### ISSUE TITLE
How to interactively add ports and id?

### ISSUE THREAD

**Issue by crystalfp** [fibo/flow-view#70]
Nice library, but how could I define ins and outs interactively? How could I assign an id interactively?
The "selector" only assign a label to the created node.
Thanks for clarifying!
mario

**Comment by fibo** [comment]
Ciao Mario (@crystalfp),

it is possible to do it. I am using flow-view extensively in a side project but it is closed source for now, so unfortunately I cannot share the code yet.

You can see an example of how to use the programmatic API here:

- [source](https://github.com/fibo/flow-view/blob/main/examples/programmatic/demo.html)
- [demo](https://fibo.github.io/flow-view/examples/programmatic/demo.html)

If by "define ins and outs interactively" you mean add inputs and outputs after node is created, by design I choose to not provide an API to do that, but instead you can delete the node and create a new one. You can define inputs and outputs using `flowView.addNodeDefinitions()`.

Regarding the selector, it just return the label of the created node because at that event you only have what the user entered.

For example in my side project, if you type any valid JSON, for example `"hello"`, `2`, `null`, `["foo"]`, that text is parsed and it creates a node with that data; if you double click the node, you can edit the data. See an example here https://app.ggbot2.com/flow.html?strategyId=c4003750&strategyKind=binance (you may need to refresh the page, to load the graph, it is still not production ready :^).

So, from the selector you get a text, then you can do whatever with this text. You can control this behaviour with `flowView.nodeTextToType()`.

For example I am using

```js
flowView.nodeTextToType((text) => nodeTextToViewType(text))
```

where `nodeTextToViewType` is defined as

```ts
/** Resolve node view type by its text. */
export const nodeTextToViewType: NodeTextToViewType = (
	text
): NodeViewType | undefined => {
	if (isPercentageNode(text)) return "perc"
	// Run `isJsonNode` before `isInfoNode` to avoid parse JSON twice.
	if (isJsonNode(text)) return "json"
	if (isInfoNode(text)) return "info"
	return undefined
}
```

I hope this helps to clarify, feel free to contact me on any channel here https://fibo.github.io/about-me/
